### ISSUE TITLE
Version 4.0.0  - Error 

### ISSUE THREAD

**Issue by danieldesouzadev** [Tapadoo/Alerter#173] opened 2019-02-24 14:28 UTC
Switching to version 3.0.1 works normally

> Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:384)
        at android.view.View.performClick(View.java:6897) 
        at android.widget.TextView.performClick(TextView.java:12693) 
        at android.view.View$PerformClick.run(View.java:26101) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
     Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class androidx.appcompat.widget.LinearLayoutCompat
     Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class androidx.appcompat.widget.LinearLayoutCompat
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.widget.LinearLayoutCompat" on path: DexPathList[[zip file "/data/app/com.mobile.project-50_42mu91CIinqqydoBPew==/base.apk", zip file "/data/app/com.mobile.project-50_42mu91CIinqqydoBPew==/split_lib_dependencies_apk.apk", zip file "/data/app/com.mobile.projectl-50_42mu91CIinqqydoBPew==/split_lib_resources_apk.apk", zip file "/data/app/com.mobile.projectl-50_42mu91CIinqqydoBPew==/split_lib_slice_0_apk.apk", zip file "/data/app/com.mobile.projectl-50_42mu91CIinqqydoBPew==/split_lib_slice_1_apk.apk", zip file "/data/app/com.mobile.projectl-50_42mu91CIinqqydoBPew==/split_lib_slice_2_apk.apk", zip file "/data/app/com.mobile.projectl-50_42mu91CIinqqydoBPew==/split_lib_slice_3_apk.apk", zip file "/data/app/com.mobile.projectl-50_42mu91CIinqqydoBPew==/split_lib_slice_4_apk.apk", zip file "/data/app/com.mobile.projectl-50_42mu91CIinqqydoBPew==/split_lib_slice_5_apk.apk", zip file "/data/app/com.mobile.projectl-50_42mu91CIinqqydoBPew==/split_lib_slice_6_apk.apk", zip file "/data/app/com.mobile.projectl-50_42mu91CIinqqydoBPew==/split_lib_slice_7_apk.apk", zip file "/data/app/com.mobile.projectl-50_42mu91CIinqqydoBPew==/split_lib_slice_8_apk.apk", zip file "/data/app/com.mobile.projectl-50_42mu91CIinqqydoBPew==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.mobile.projectl-50_42mu91CIinqqydoBPew==/lib/arm64, /system/lib64, /system/vendor/lib64]]

>

**Comment by kpmmmurphy** [comment] 2019-02-28 17:04
Hi @danieldesouzadev, I've added a fix for this in version 4.0.1. I believe this was caused by the user of `LinearLayoutCompat`, which I have removed. Please test and let me know if it has been resolved!

**Closed** 2019-03-20 10:36 UTC

**Comment by zzxjl1** [comment] 2019-05-28 09:19
version 4.0.2 still has this problem

**Comment by zzxjl1** [comment] 2019-05-28 09:21
Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.idealbroker.app-gNYTCDif1pNFuq8zCw0KLg==/base.apk", zip file "/data/app/com.idealbroker.app-gNYTCDif1pNFuq8zCw0KLg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.idealbroker.app-gNYTCDif1pNFuq8zCw0KLg==/split_lib_resources_apk.apk", zip file "/data/app/com.idealbroker.app-gNYTCDif1pNFuq8zCw0KLg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.idealbroker.app-gNYTCDif1pNFuq8zCw0KLg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.idealbroker.app-gNYTCDif1pNFuq8zCw0KLg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.idealbroker.app-gNYTCDif1pNFuq8zCw0KLg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.idealbroker.app-gNYTCDif1pNFuq8zCw0KLg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.idealbroker.app-gNYTCDif1pNFuq8zCw0KLg==/split_lib_slice_5_apk.apk", zip file "/data/app/com.idealbroker.app-gNYTCDif1pNFuq8zCw0KLg==/split_lib_slice_6_apk.apk", zip file "/data/app/com.idealbroker.app-gNYTCDif1pNFuq8zCw
2019-05-28 17:14:41.966 9465-9465/? E/AndroidRuntime: FATAL EXCEPTION: main
